require('luasnip').filetype_extend("javascript", { "javascriptreact", "typescriptreact" })
require('luasnip').filetype_extend("javascript", { "html" })
require('luasnip').filetype_extend("javascriptreact", { "html" })
require('luasnip').filetype_extend("typescriptreact", { "html" })
require("luasnip.loaders.from_vscode").lazy_load()
